import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import markdown
from fastapi import HTTPException
from app.core.config import settings

logger = logging.getLogger(__name__)


def render_email_html(summary_markdown: str, filename: str) -> str:
    """Convert markdown summary to styled HTML email."""
    body_html = markdown.markdown(summary_markdown)
    return f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 20px; }}
    .container {{ max-width: 680px; margin: 0 auto; background: white; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }}
    .header {{ background: linear-gradient(135deg, #0f1923 0%, #1a3a5c 100%); padding: 32px 40px; }}
    .header h1 {{ color: #e8f4ff; margin: 0; font-size: 22px; font-weight: 700; letter-spacing: -0.3px; }}
    .header p {{ color: #7ab3d4; margin: 6px 0 0; font-size: 13px; }}
    .badge {{ display: inline-block; background: #00d4aa; color: #0f1923; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 10px; }}
    .content {{ padding: 36px 40px; }}
    .content h2 {{ color: #0f1923; font-size: 16px; border-bottom: 2px solid #e8f0fe; padding-bottom: 8px; margin-top: 28px; }}
    .content p {{ color: #374151; line-height: 1.7; font-size: 14px; }}
    .content ul {{ color: #374151; line-height: 1.8; font-size: 14px; padding-left: 20px; }}
    .content li {{ margin-bottom: 4px; }}
    .content strong {{ color: #0f1923; }}
    .footer {{ background: #f8fafc; padding: 20px 40px; border-top: 1px solid #e5e9f0; }}
    .footer p {{ color: #9ca3af; font-size: 12px; margin: 0; }}
    .filename-tag {{ background: #eff6ff; color: #3b82f6; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-family: monospace; }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>📊 Sales Insight Report</h1>
      <p>Generated by Rabbitt AI Sales Automator</p>
      <span class="badge">Q1 2026 Analysis</span>
    </div>
    <div class="content">
      <p style="color:#6b7280; font-size:13px; margin-top:0;">
        Source file: <span class="filename-tag">{filename}</span>
      </p>
      {body_html}
    </div>
    <div class="footer">
      <p>This report was automatically generated by Rabbitt AI. For questions, contact your team lead.</p>
    </div>
  </div>
</body>
</html>"""


async def send_email_smtp(to_email: str, subject: str, html_content: str, text_content: str) -> None:
    """Send email via SMTP."""
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = f"{settings.FROM_NAME} <{settings.FROM_EMAIL}>"
        msg["To"] = to_email

        msg.attach(MIMEText(text_content, "plain"))
        msg.attach(MIMEText(html_content, "html"))

        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
            server.sendmail(settings.FROM_EMAIL, to_email, msg.as_string())

        logger.info(f"Email sent via SMTP to {to_email}")
    except Exception as e:
        logger.error(f"SMTP send error: {e}")
        raise HTTPException(status_code=502, detail=f"Email delivery failed: {str(e)}")


async def send_email_sendgrid(to_email: str, subject: str, html_content: str, text_content: str) -> None:
    """Send email via SendGrid."""
    try:
        from sendgrid import SendGridAPIClient
        from sendgrid.helpers.mail import Mail, Content, To

        sg = SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
        message = Mail(
            from_email=(settings.FROM_EMAIL, settings.FROM_NAME),
            to_emails=To(to_email),
            subject=subject,
        )
        message.add_content(Content("text/plain", text_content))
        message.add_content(Content("text/html", html_content))

        response = sg.send(message)
        logger.info(f"Email sent via SendGrid to {to_email}, status: {response.status_code}")
    except Exception as e:
        logger.error(f"SendGrid send error: {e}")
        raise HTTPException(status_code=502, detail=f"Email delivery failed: {str(e)}")


async def send_insight_email(to_email: str, summary: str, filename: str) -> None:
    """Dispatch the AI summary email to recipient."""
    subject = f"📊 Sales Insight Report — {filename}"
    html_content = render_email_html(summary, filename)
    text_content = f"Sales Insight Report\n\nSource: {filename}\n\n{summary}"

    provider = settings.EMAIL_PROVIDER.lower()
    if provider == "sendgrid":
        if not settings.SENDGRID_API_KEY:
            raise HTTPException(status_code=500, detail="SENDGRID_API_KEY not configured.")
        await send_email_sendgrid(to_email, subject, html_content, text_content)
    else:
        if not settings.SMTP_USER or not settings.SMTP_PASSWORD:
            raise HTTPException(status_code=500, detail="SMTP credentials not configured.")
        await send_email_smtp(to_email, subject, html_content, text_content)
